/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetocassino;

import java.util.ArrayList;

/**
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(ArrayList<Jogador> jogadores) {
        initComponents();
        if(jogadores.isEmpty()){
            btnAdicionarFichas.setEnabled(false);
            btnVisualizarJogadores.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        btnAdicionarJogador = new javax.swing.JButton();
        btnAdicionarFichas = new javax.swing.JButton();
        labelTextoApresentacao = new javax.swing.JLabel();
        btnVisualizarJogadores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTitulo.setText("Bem Vindo ao Cassino CSFI");

        btnAdicionarJogador.setText("Adicionar Jogador");
        btnAdicionarJogador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdicionarJogadorMouseClicked(evt);
            }
        });

        btnAdicionarFichas.setText("Adicionar Fichas");

        labelTextoApresentacao.setText("Adicione o jogador ou adicione fichas a um jogador existente. ");

        btnVisualizarJogadores.setText("Visualizar Jogadores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelTextoApresentacao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdicionarJogador)
                                .addGap(56, 56, 56)
                                .addComponent(btnAdicionarFichas))
                            .addComponent(labelTitulo))))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnVisualizarJogadores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(labelTextoApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarJogador)
                    .addComponent(btnAdicionarFichas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualizarJogadores)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarJogadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarJogadorMouseClicked
        TelaCadastroJogador telaJogador = new TelaCadastroJogador();
        telaJogador.setVisible(true);
    }//GEN-LAST:event_btnAdicionarJogadorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarFichas;
    private javax.swing.JButton btnAdicionarJogador;
    private javax.swing.JButton btnVisualizarJogadores;
    private javax.swing.JLabel labelTextoApresentacao;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
